services:
  - type: web
    name: finn-vev-proxy
    runtime: node
    buildCommand: "npm install --production"
    startCommand: "node server.js"
    envVars:
      - key: FINN_CLIENT_ID
        value: # Add your FINN Client ID here
      - key: FINN_CLIENT_SECRET
        value: # Add your FINN Client Secret here
    autoDeploy: false